// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-U-2Z8MvIfkIR8qM_CAeib-bz6bCMiM',
    appId: '1:1030830152772:web:d4460f5c18117750ebf011',
    messagingSenderId: '1030830152772',
    projectId: 'hackathon-fda02',
    authDomain: 'hackathon-fda02.firebaseapp.com',
    storageBucket: 'hackathon-fda02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZxGYrH6AnqAeZAcTbJErFZgVpkl6TNw',
    appId: '1:1030830152772:android:5946ba3ac9c634c7ebf011',
    messagingSenderId: '1030830152772',
    projectId: 'hackathon-fda02',
    storageBucket: 'hackathon-fda02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYeyDycfb49IF1NGtsUtlNpT0P1cUL2I',
    appId: '1:1030830152772:ios:b1d7bff248d18ec7ebf011',
    messagingSenderId: '1030830152772',
    projectId: 'hackathon-fda02',
    storageBucket: 'hackathon-fda02.appspot.com',
    iosBundleId: 'com.blindma1den.hackatonteam.flutterApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYeyDycfb49IF1NGtsUtlNpT0P1cUL2I',
    appId: '1:1030830152772:ios:b1d7bff248d18ec7ebf011',
    messagingSenderId: '1030830152772',
    projectId: 'hackathon-fda02',
    storageBucket: 'hackathon-fda02.appspot.com',
    iosBundleId: 'com.blindma1den.hackatonteam.flutterApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-U-2Z8MvIfkIR8qM_CAeib-bz6bCMiM',
    appId: '1:1030830152772:web:9c17610bae5e72dfebf011',
    messagingSenderId: '1030830152772',
    projectId: 'hackathon-fda02',
    authDomain: 'hackathon-fda02.firebaseapp.com',
    storageBucket: 'hackathon-fda02.appspot.com',
  );
}
